const products = [
  {
    id: 'shamsa-mix',
    name: 'Shamsa Mix',
    category: 'Special Collection',
    badge: 'Premium',
    badgeClass: '',
    image: 'Pics/shamsa-special.jpeg',
    price: 1099,
    oldPrice: null,
    reviews: 47,
    shortDesc: 'A soul-stirring dark oud attar with layers of smoked agarwood, warm spice, and earthy depth.',
    modalBadge: 'Deep & Woody',
    topNotes: 'Cardamom, Black Pepper',
    heartNotes: 'Agarwood Oud, Sandalwood',
    baseNotes: 'Musk, Amber Resin',
    projection: 88
  },
  {
    id: 'blue-ocean-zoya',
    name: 'Blue Ocean And Zoya',
    category: 'Western Inspired',
    badge: 'Duo set',
    badgeClass: '',
    image: 'Pics/2-duo.jpeg',
    price: 1499,
    oldPrice: null,
    reviews: 34,
    shortDesc: 'A luxurious inspired interpretation of western elegance — warm amber, velvety musk, and exotic florals.',
    modalBadge: 'Soft & Floral',
    topNotes: 'Bergamot, Neroli',
    heartNotes: 'White Musk, Rose Absolute',
    baseNotes: 'Vanilla, Sandalwood',
    projection: 75
  },
  {
    id: 'sabaya-gucci',
    name: 'Sabaya Gucci Mix',
    category: 'Signature Blend',
    badge: 'New ✨',
    badgeClass: 'new',
    image: 'Pics/shamsa-special.jpeg',
    price: 1500,
    oldPrice: null,
    reviews: 29,
    shortDesc: 'A refined, crystal-clear attar with crisp green freshness and a powdery soft dry-down.',
    modalBadge: 'Fresh & Clean',
    topNotes: 'Green Apple, Lemon Zest',
    heartNotes: 'Iris, Aquatic Musk',
    baseNotes: 'Cedarwood, White Amber',
    projection: 70
  },
  {
    id: 'royals-trio',
    name: 'Royals Trio Set',
    category: 'Gift Set',
    badge: 'Trio Set 🎁',
    badgeClass: 'sale',
    image: 'Pics/1.jpeg',
    price: 850,
    oldPrice: 999,
    reviews: 21,
    shortDesc: 'Our three most-loved bestsellers — Oud Ashiq, Gucci & Havol — curated together in a luxurious gift box.',
    modalBadge: 'Exclusive Bundle',
    topNotes: 'Cardamom, Bergamot, Lemon',
    heartNotes: 'Oud, Rose, Iris',
    baseNotes: 'Amber, Musk, Sandalwood',
    projection: 92
  },
    {
    id: 'royal-trio',
    name: ' Trio Set',
    category: 'Gift Set',
    badge: 'Trio Set',
    badgeClass: 'sale',
    image: 'Pics/2.jpeg',
    price: 850,
    oldPrice: 999,
    reviews: 26,
    shortDesc: 'Our three most-loved bestsellers — Rumba Lord and invictuc — curated together in a luxurious gift box.',
    modalBadge: 'Exclusive Bundle',
    topNotes: 'Cardamom, Bergamot, Lemon',
    heartNotes: 'Rumba Lord and invictuc',
    baseNotes: 'Amber, Musk, Sandalwood',
    projection: 80
  },
  {
    id: 'trio-royals',
    name: 'Trio Set',
    category: 'Signature Collection',
    badge: 'Best Seller',
    badgeClass: '',
    image: 'Pics/3.png',
    price: 999,
    oldPrice: 1200,
    reviews: 58,
    shortDesc: 'Experience the perfect blend of elegance and luxury with our exclusive trio set featuring White Musk, Oud Al Madinah, and Sabaya',
    modalBadge: 'Deep & Woody',
    topNotes: 'Agarwood, Saffron',
    heartNotes: 'Rose, Patchouli',
    baseNotes: 'Musk, Amber',
    projection: 95
  },
  {
    id: 'golden-musk',
    name: 'Golden Musk',
    category: 'Premium Collection',
    badge: 'Premium',
    badgeClass: '',
    image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=1200',
    price: 10900,
    oldPrice: null,
    reviews: 42,
    shortDesc: 'Soft premium musk fragrance made for elegant and classy personalities.',
    modalBadge: 'Soft & Elegant',
    topNotes: 'White Musk, Floral',
    heartNotes: 'Jasmine, Lily',
    baseNotes: 'Vanilla, Sandalwood',
    projection: 80
  },
  {
    id: 'black-amber',
    name: 'Black Amber',
    category: 'Luxury Collection',
    badge: 'Luxury',
    badgeClass: '',
    image: 'https://images.unsplash.com/photo-1615634260167-c8cdede054de?q=80&w=1200',
    price: 16500,
    oldPrice: null,
    reviews: 65,
    shortDesc: 'Rich amber fragrance with powerful long-lasting premium aroma.',
    modalBadge: 'Rich & Powerful',
    topNotes: 'Amber, Bergamot',
    heartNotes: 'Oud, Spicy Notes',
    baseNotes: 'Patchouli, Dark Musk',
    projection: 90
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = products;
}
